# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  ljsherlock.com:
    site_hosts:
      - canonical: ljsherlock.dev
        # redirects:
        #   - www.ljsherlock.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: me@ljsherlock.com
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
