sudo: false
language: php
php:
  - 7.1
  - 7.0
  - 5.6

global:
  - THEME_DIR=./site/web/app/themes/ljsherlock/
  - SITE_DIR=./site/
  - TRELLIS_DIR=./trellis/

before_install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - npm install -g grunt

install:
    - cd $THEME_DIR
    - composer install --optimize-autoloader

script:
  - cd $TRAVIS_BUILD_DIR
  - phpcs --standard=ruleset.xml --extensions=php --ignore=web/wp/,web/app/plugins/,vendor/ -n -s .
