sudo: false
language: php
php:
  - 7.1
  - 7.0

global:
  - THEME_DIR=./site/web/app/themes/ljsherlock/
  - SITE_DIR=./site/
  - TRELLIS_DIR=./trellis/

install: composer install --no-dev --no-scripts --quiet --optimize-autoloader

before_script: composer require atoum/atoum

script: vendor/bin/atoum
