# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: MissionDiscipline1990;lewis

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: MissionDiscipline1990;lewis
    salt: ",S$/]vsLX*>2gw;M)xoy)%9$s!Pr&PU,:t4[?VQ/?BA)5P>X<IeXq?FD[i*$![gv"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  ljsherlock.com:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "ziJ!H6H_mw(w`.Qi{3v7btpSju<dd:TS(?fnGnoeI+.)l2?5zy_VjO#ScdQ/dtfn"
      secure_auth_key: "|;hLv1an2RtOGU64D>oT_np|0DS)2C@dh^xi&<@^|<*b&DLR3X&AEcSr}/x%4>n/"
      logged_in_key: "Rh]vNk.z(ob*Iol%N,{Lpz+_^g<v*gnGSdV`3LG2n7q$u_n;ywS3d@J9*]wDe3e+"
      nonce_key: "]z=y+Tu`;}CJ2e@LiVblbHrOTJ85F&9E|@fdOS6t#[eq0qw)XFcQ|v5O=C>ZTf;-"
      auth_salt: "R40>LgLfm+C7|ze1rYhp2<onp4IH)P(.XGXmNXQsKz;6s;d+k#yk6:?yeWXJ9D`E"
      secure_auth_salt: "G5TA80v[b6HrhtiZeK1g;J0fC2ex**>YuV0o1#oM<1hoZ-otIl:y$sbF9ZRENXYw"
      logged_in_salt: ".<>]D2VjoI)17eR**[kt6|r}14F_dx2$kV0/X(Wg1E_EB&@Jy!k9w-}!v0dIVO:-"
      nonce_salt: "B&8tVbjg0-Ql>Uzp&?g9l@V{nv@JSE.v>.uhGD5U|)6CT;f+1;X*uC88zxZEe#of"
  f3architects.co.uk:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "ziJ!H6H_mw(w`.Qi{3v7btpSju<dd:TS(?fnGnoeI+.)l2?5zy_VjO#ScdQ/dtfn"
      secure_auth_key: "|;hLv1an2RtOGU64D>oT_np|0DS)2C@dh^xi&<@^|<*b&DLR3X&AEcSr}/x%4>n/"
      logged_in_key: "Rh]vNk.z(ob*Iol%N,{Lpz+_^g<v*gnGSdV`3LG2n7q$u_n;ywS3d@J9*]wDe3e+"
      nonce_key: "]z=y+Tu`;}CJ2e@LiVblbHrOTJ85F&9E|@fdOS6t#[eq0qw)XFcQ|v5O=C>ZTf;-"
      auth_salt: "R40>LgLfm+C7|ze1rYhp2<onp4IH)P(.XGXmNXQsKz;6s;d+k#yk6:?yeWXJ9D`E"
      secure_auth_salt: "G5TA80v[b6HrhtiZeK1g;J0fC2ex**>YuV0o1#oM<1hoZ-otIl:y$sbF9ZRENXYw"
      logged_in_salt: ".<>]D2VjoI)17eR**[kt6|r}14F_dx2$kV0/X(Wg1E_EB&@Jy!k9w-}!v0dIVO:-"
      nonce_salt: "B&8tVbjg0-Ql>Uzp&?g9l@V{nv@JSE.v>.uhGD5U|)6CT;f+1;X*uC88zxZEe#of"
