# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: 2708f39a82431b459a1fd73a0c685372

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: "035e7b49345a3e322634913acafae0ba"
    salt: "fOc2szbY3wCcD4xKSpDHjck6g4ZvYI"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  ljsherlock.com:
    env:
      db_password: "a05666432e779c4010329869a1fa302d"
      # Generate your keys here: https://roots.io/salts.html
    auth_key: "j9^xC|r6-unZoGN(`NoP&8,PrzHHv70vKDVYkq#utw67%%=dxv>@Y.rc)lh#;IQX"
    secure_auth_key: "4+#C;%?!Cvd]c$#9|&wdRWz}X[,V3kEO^=fp3o+9.xE5LInc(:0nL-S#5cK5VdW:"
    logged_in_key: "L:<Bd%/C+Pt(RZ!`=Wj<lr@_qEs$*kaZdPAvA0GF]ss(8cnPNhxVyiEnJR%Zu0eE"
    nonce_key: "Q9Azxu]eA!t:}ymk7mmB}XlK|#k(F)T@Wmsy!hMeUW#H>s8&MD#Iec#IIjs?JqHE"
    auth_salt: "x2)!d$+iRekftfA=,vXuHwwL]|IJB,UIR@azEKppH>)anCq1<Zqt9M$6RKr!HgN^"
    secure_auth_salt: ",FxMJ1XJ/]w%qa:?.A8N@MpXkwS%I(Bt92//`{:b(BC%O.`GUuYoUu!_G%T@a#=,"
    logged_in_salt: "cGF(Qkc1@8R[u9kD&LlNo0;9D_IZF*c??6MZ8>|+T#lzR-`-4ixnVRO4-_XAYkW0"
    nonce_salt: "%%<ac-LV4hu?SXJ|;|pc|Hi]R$Q/q6-AC?43N]@25kZ}e@#42J9tqX|<J#xV5G8E"
